# Generated by Django 4.2.7 on 2025-12-08 17:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Όνομα')),
                ('location', models.CharField(max_length=100, verbose_name='Τοποθεσία')),
            ],
            options={
                'verbose_name': 'Πανεπιστήμιο',
                'verbose_name_plural': 'Πανεπιστήμια',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Όνομα Μαθήματος')),
                ('department', models.CharField(max_length=200, verbose_name='Τμήμα')),
                ('semester', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Εξάμηνο')),
                ('category', models.CharField(choices=[('Υποχρεωτικό', 'Υποχρεωτικό'), ('Επιλογής', 'Επιλογής'), ('Εργαστήριο', 'Εργαστήριο')], max_length=20, verbose_name='Κατηγορία')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.university', verbose_name='Πανεπιστήμιο')),
            ],
            options={
                'verbose_name': 'Μάθημα',
                'verbose_name_plural': 'Μαθήματα',
                'ordering': ['university', 'department', 'semester', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_period', models.CharField(choices=[('Ιουνίου', 'Ιουνίου'), ('Σεπτεμβρίου', 'Σεπτεμβρίου'), ('Φεβρουαρίου/Ιανουαρίου', 'Φεβρουαρίου/Ιανουαρίου')], max_length=30, verbose_name='Περίοδος Εξέτασης')),
                ('exam_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Έτος')),
                ('group_name', models.CharField(blank=True, help_text='π.χ., Ομάδα Α, Set 2', max_length=50, null=True, verbose_name='Όνομα Ομάδας')),
                ('file', models.FileField(help_text='PDF, PNG, JPG, DOCX', upload_to='exam_papers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'docx'])], verbose_name='Αρχείο')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Σημειώσεις Διαχειριστή')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.subject', verbose_name='Μάθημα')),
            ],
            options={
                'verbose_name': 'Θέμα Εξέτασης',
                'verbose_name_plural': 'Θέματα Εξέτασης',
                'ordering': ['-exam_year', 'exam_period', 'subject'],
            },
        ),
    ]
