# Generated by Django 4.2.7 on 2025-12-08 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exampaper',
            options={'ordering': ['-exam_year', 'exam_period', 'subject'], 'verbose_name': 'Έγγραφο', 'verbose_name_plural': 'Έγγραφα'},
        ),
        migrations.AddField(
            model_name='exampaper',
            name='document_type',
            field=models.CharField(choices=[('Θέμα Εξεταστικής', 'Θέμα Εξεταστικής'), ('Σημείωση', 'Σημείωση')], default='Θέμα Εξεταστικής', max_length=30, verbose_name='Τύπος Εγγράφου'),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='exam_period',
            field=models.CharField(blank=True, choices=[('Ιουνίου', 'Ιουνίου'), ('Σεπτεμβρίου', 'Σεπτεμβρίου'), ('Φεβρουαρίου/Ιανουαρίου', 'Φεβρουαρίου/Ιανουαρίου')], help_text='Απαιτείται μόνο για θέματα εξεταστικής', max_length=30, null=True, verbose_name='Περίοδος Εξέτασης'),
        ),
        migrations.AlterField(
            model_name='exampaper',
            name='exam_year',
            field=models.IntegerField(blank=True, help_text='Απαιτείται μόνο για θέματα εξεταστικής', null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Έτος'),
        ),
    ]
