# Generated by Django 4.2.7 on 2025-12-09 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_exampaper_options_exampaper_document_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exampaper',
            options={'ordering': ['-exam_year', '-created_at', 'subject'], 'verbose_name': 'Έγγραφο', 'verbose_name_plural': 'Έγγραφα'},
        ),
    ]
